//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GKHUBEntities : DbContext
    {
        public GKHUBEntities()
            : base("name=GKHUBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biology> Biologies { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Physic> Physics { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Chemistry> Chemistries { get; set; }
        public virtual DbSet<CurrentAffair> CurrentAffairs { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Polity> Polities { get; set; }
        public virtual DbSet<Economic> Economics { get; set; }
        public virtual DbSet<Geography> Geographies { get; set; }
    }
}
